name: Terraform Plan and Apply

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'aws_deploy_infrastructure/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: 1.12.1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      working-directory: ./aws_deploy_infrastructure
      run: terraform init

    - name: Terraform Format
      working-directory: ./aws_deploy_infrastructure  
      run: terraform fmt

    - name: Terraform Plan
      id: plan
      working-directory: ./aws_deploy_infrastructure
      env:
        TF_VAR_db_admin_name: ${{ secrets.DB_ADMIN_NAME }}
        TF_VAR_db_admin_pwd: ${{ secrets.DB_ADMIN_PWD }}
      run: |
        terraform plan -detailed-exitcode -out=tfplan
        echo "Plan created successfully"
        
    - name: Publish Terraform Plan
      id: plan-output
      working-directory: ./aws_deploy_infrastructure
      run: |
        echo "## Terraform Plan Output" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
        terraform show -no-color tfplan >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY

  terraform_apply:
    needs: terraform
    runs-on: ubuntu-latest
    environment: production  # This environment needs to be configured with required reviewers
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: 1.12.1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      working-directory: ./aws_deploy_infrastructure
      run: terraform init

    - name: Terraform Plan (regenerate)
      working-directory: ./aws_deploy_infrastructure
      env:
        TF_VAR_db_admin_name: ${{ secrets.DB_ADMIN_NAME }}
        TF_VAR_db_admin_pwd: ${{ secrets.DB_ADMIN_PWD }}
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: ./aws_deploy_infrastructure
      env:
        TF_VAR_db_admin_name: ${{ secrets.DB_ADMIN_NAME }}
        TF_VAR_db_admin_pwd: ${{ secrets.DB_ADMIN_PWD }}
      run: terraform apply -auto-approve tfplan
