name: Terraform Plan

on:
  workflow_dispatch:

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: 1.12.1  # Specify your desired Terraform version

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init
      working-directory: ./aws_deploy_infrastructure
      run: terraform init

    - name: Terraform Format
      working-directory: ./aws_deploy_infrastructure    
      run: terraform fmt

    - name: Terraform Plan
      id: plan
      working-directory: ./aws_deploy_infrastructure
      # env:
      #   TF_VAR_ai_key: ${{ secrets.ANTHROPIC_API_KEY }}
      run: terraform plan

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
